on:
  push:
    branches:
      - master
    

jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - name: 'maszen testing'
        run: pwd

      - name: 'maszen printing'
        run: echo mazen

